css-brochure-form
Jason-Humphrey/c0121-code-solutions pull request #20
Opened 2021-01-22 21:24 UTC by Jason-Humphrey

![Screen Shot 2021-01-22 at 2 55 23 PM](https://user-images.githubusercontent.com/76718667/105548890-d7934e00-5cc5-11eb-8d17-bfef765df7f4.png)

2021-01-22 21:29 UTC, Jason-Humphrey commented
Hopefully this isn't a big mess. I tried to incorporate your changes as suggested. I was still having trouble so i started over. I know you don't like to hear it, but i was up till 5 am working on this. Afraid of falling behind. Which i already am.

2021-01-23 00:08 UTC, codingcodymiller requested changes
Nice work so far, man!! Couple of notes here. A lot have to do with formatting and indentation, make sure you are paying attention to those 👀

2021-01-23 00:08 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  }
This can be removed.

2021-01-23 00:08 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +    margin-right: 15%;
Woah, that's a lot of margin! What is this doing for you? It should probably be removed.

2021-01-23 00:08 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  input, select {
This shouldn't be indented

2021-01-23 00:08 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +   body {
This shouldn't be indented

2021-01-23 00:08 UTC, codingcodymiller commented on css-brochure-form/styles.css
> +  font
This needs to be removed.

2021-01-23 01:05 UTC, Jason-Humphrey commented on css-brochure-form/styles.css
> +  font
all of those lines need to be removed? if i take off border the ugly border comes back 
![Screen Shot 2021-01-22 at 7 02 25 PM](https://user-images.githubusercontent.com/76718667/105563625-70d15d00-5ce4-11eb-946f-143bf65c4ba9.png)

2021-01-26 02:38 UTC, codingcodymiller approved these changes
Nice work!!! 🎉

2021-01-26 02:54 UTC, merged