css-three-column-layout
Jason-Humphrey/c0121-code-solutions pull request #21
Opened 2021-01-24 20:41 UTC by Jason-Humphrey

<img width="964" alt="Screen Shot 2021-01-24 at 2 32 02 PM" src="https://user-images.githubusercontent.com/76718667/105642899-2bcb3900-5e52-11eb-9638-818f6162da1f.png">

2021-01-26 21:27 UTC, codingcodymiller requested changes
Hey Jason! A couple notes:

You have multiple CSS rules for the same element (ex: `section`, `body`). Please combine these.

Check each property in your CSS one by one, and delete properties that do not affect the output.

Your column classes can be one class, since the styling for all three is the same.

2021-02-01 02:11 UTC, Jason-Humphrey commented
<img width="974" alt="Screen Shot 2021-01-31 at 8 01 34 PM" src="https://user-images.githubusercontent.com/76718667/106406935-76bff000-6400-11eb-821e-9bb7f3310ab6.png">

2021-02-01 02:18 UTC, thebearingedge requested changes
Looking really good so far, you just need to try and solve this one without positioning.

2021-02-01 02:18 UTC, thebearingedge commented on css-three-column-layout/styles.css
> +  z-index: 2;
You shouldn't need positioning for this assignment. It can be done by putting the images inside of divs and giving the divs a background color of white.

2021-02-01 02:18 UTC, thebearingedge commented on css-three-column-layout/styles.css
> +  position: fixed;
You should be able to do this without position. Position is an incredibly powerful part of CSS, so it's best to try to use document flow and the box model instead.

2021-02-04 07:02 UTC, Jason-Humphrey commented
<img width="1011" alt="Screen Shot 2021-02-04 at 12 40 04 AM" src="https://user-images.githubusercontent.com/76718667/106856744-95361d80-6684-11eb-8095-975fff0e645e.png">

2021-02-04 17:22 UTC, thebearingedge approved these changes

2021-02-04 19:19 UTC, merged