Javascript data model
Jason-Humphrey/c0121-code-solutions pull request #26
Opened 2021-01-26 21:54 UTC by Jason-Humphrey

![Screen Shot 2021-01-26 at 1 06 13 PM](https://user-images.githubusercontent.com/76718667/105910593-c6607f00-5fee-11eb-96af-7186bc5c10ea.png)

2021-01-26 23:15 UTC, codingcodymiller requested changes
Great job so far! Please see my note:

2021-01-26 23:15 UTC, codingcodymiller commented on javascript-data-model/order-history.js
> +  },
Rather than having individual properties for each item, this would be better to be an array. Make sure you update your other order objects to reflect this change too!

2021-01-27 16:02 UTC, Jason-Humphrey commented on javascript-data-model/order-history.js
> +  },
<img width="594" alt="Screen Shot 2021-01-27 at 9 54 50 AM" src="https://user-images.githubusercontent.com/76718667/106017908-9cf33200-6086-11eb-9ed1-655f8f3368be.png">
<img width="594" alt="Screen Shot 2021-01-27 at 9 55 10 AM" src="https://user-images.githubusercontent.com/76718667/106017924-a086b900-6086-11eb-9a3d-ea11dbe52335.png">

2021-01-27 18:52 UTC, codingcodymiller approved these changes
Nice work!!! 🎉

2021-01-27 20:37 UTC, merged