javascript-functions
Jason-Humphrey/c0121-code-solutions pull request #27
Opened 2021-01-27 02:11 UTC by Jason-Humphrey

![Screen Shot 2021-01-26 at 8 10 54 PM](https://user-images.githubusercontent.com/76718667/105932546-a17e0300-6012-11eb-83f8-c9187f14739d.png)

2021-01-27 18:38 UTC, codingcodymiller requested changes
Hey Jason, one fix here:

2021-01-27 18:38 UTC, codingcodymiller commented on javascript-functions/main.js
> +}
Please do this by accessing the property inside of the function block, not by deconstruction.

2021-01-27 20:49 UTC, Jason-Humphrey commented on javascript-functions/main.js
> +}
![Screen Shot 2021-01-27 at 2 45 39 PM](https://user-images.githubusercontent.com/76718667/106051988-be681400-60ae-11eb-9682-a770762b87e6.png)
![Screen Shot 2021-01-27 at 2 44 01 PM](https://user-images.githubusercontent.com/76718667/106052000-c1630480-60ae-11eb-875c-fac573248dbb.png)

2021-01-28 16:51 UTC, thebearingedge approved these changes

2021-01-28 22:42 UTC, merged