css-media-queries
Jason-Humphrey/c0121-code-solutions pull request #40
Opened 2021-02-04 21:31 UTC by Jason-Humphrey

https://user-images.githubusercontent.com/76718667/106957761-0fef4f00-66fe-11eb-9b90-cf387402cba2.mp4

https://user-images.githubusercontent.com/76718667/106957784-154c9980-66fe-11eb-8b29-e6fb0bf66a77.mp4

https://user-images.githubusercontent.com/76718667/106957797-1a114d80-66fe-11eb-91d4-e3c3f1180ab8.mp4

2021-02-04 23:09 UTC, thebearingedge requested changes

2021-02-04 23:09 UTC, thebearingedge commented on css-media-queries/meta-viewport.html
> +
You will need to make sure to use the correct meta tag here and test your code using the mobile simulation of the dev tools per the instructions.

2021-02-05 04:04 UTC, Jason-Humphrey commented on css-media-queries/meta-viewport.html
> +
https://user-images.githubusercontent.com/76718667/106988234-e00f6e00-6734-11eb-902b-b95f1a182a6f.mp4

2021-02-05 15:21 UTC, thebearingedge approved these changes

2021-02-06 20:37 UTC, merged