css-two-column-layout
Jason-Humphrey/c0121-code-solutions pull request #51
Opened 2021-02-18 01:14 UTC by Jason-Humphrey

![Screen Shot 2021-02-17 at 6 45 16 PM](https://user-images.githubusercontent.com/76718667/108289614-53ad7400-7154-11eb-9245-45dde600bb58.png)

2021-02-22 20:59 UTC, thebearingedge requested changes

2021-02-22 20:59 UTC, thebearingedge commented on css-two-column-layout/styles.css
> +.column-one {
You can use one class `.column` instead of two, since you want all of the columns to pretty much behave the same.

2021-02-22 20:59 UTC, thebearingedge commented on css-two-column-layout/styles.css
> +  margin: 6.875;
I see that this `margin` doesn't have a unit associated with it. If you delete this property, does the code still work the same?

2021-02-23 05:37 UTC, Jason-Humphrey commented
<img width="706" alt="Screen Shot 2021-02-22 at 11 34 02 PM" src="https://user-images.githubusercontent.com/76718667/108806277-dbd1b600-7566-11eb-8edf-2a0c4e3b2ae7.png">

2021-02-23 06:05 UTC, codingcodymiller approved these changes

2021-02-23 06:23 UTC, merged