javascript-light-bulb
Jason-Humphrey/c0121-code-solutions pull request #55
Opened 2021-02-21 00:41 UTC by Jason-Humphrey

https://user-images.githubusercontent.com/76718667/108612122-1bec3980-73ab-11eb-8b6d-9db97b1ba8df.mp4

2021-02-21 00:48 UTC, codingcodymiller requested changes
Nice work so far!! Please see my notes

2021-02-21 00:48 UTC, codingcodymiller commented on javascript-light-bulb/main.js
> +  }
Instead of doing this in two conditionals, this can be done in one. If the bulb is `on`, you want it to now be `off`, and the room would be `dark` as well.

2021-02-21 00:48 UTC, codingcodymiller commented on javascript-light-bulb/index.html
> +<body class="light dark">
This should start with just `dark`

2021-02-21 00:48 UTC, codingcodymiller commented on javascript-light-bulb/index.html
> +      <div class="light-bulb on off">
This should start with just `off`

2021-02-21 03:33 UTC, Jason-Humphrey commented
https://user-images.githubusercontent.com/76718667/108614779-2ca8a980-73c3-11eb-8a21-272bc9758a42.mp4

2021-02-22 21:17 UTC, thebearingedge approved these changes

2021-02-22 23:53 UTC, merged